### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [upvalue/tekne#22]
Hello,

I want to contribute. I designed a logo for meditations. Also, I can design anything you want. 
If you want to see my portfolio you can look at my github profile. 

I will waiting feedback. If you want it, i will send a pr.

![medidation](https://user-images.githubusercontent.com/36298335/41937229-7131174a-7998-11e8-9383-b78bf73a0e18.jpg)

**Comment by upvalue** [comment]
Thank you very nmmuch! Go ahead and make a pull request.

**Comment by reallinfo** [comment]
Oh, okey! Which color do you prefer? turquoise or green?

**Comment by upvalue** [comment]
Turquoise

**Comment by reallinfo** [comment]
I sent a pr. Btw, Do you need a logo for another project?

https://github.com/ioddly/meditations/pull/23

**Comment by upvalue** [comment]
Thank you! Meditations is basically the only project of mine that anyone else uses, so I think I'm good. I added an attribution to the README for you.
