### ISSUE TITLE
pongo2: template "habits" is undefined

### ISSUE THREAD

**Issue by t3h2mas** [upvalue/tekne#5]
Followed the getting started steps and got this message

**Comment by t3h2mas** [comment]
This happened when I ran the
`./meditations serve --port 8080 --database sample.sqlite3 --migrate` from my gobin folder instead of the project source folder. Closing as nonissue

**Comment by upvalue** [comment]
It probably should work from gobin for ease of installation, but although I got it to load templates with that commit there's still one or two things I need to do in order to get that working.

Let me know if you run into anything else.
